#+TITLE: Javascript Notes
#+AUTHOR: Lalit Kumar
#+EMAIL: lalitkumar.meena.lk@gmail.com
#+OPTIONS: toc:nil

* JavaScript
** Notes
*** For making a NodeList an Array
#+begin_src javascript
  var nodesArray = [].slice.call(document.querySelectorAll('div'));
#+end_src
*** For checking any function execution time, use something like this
#+begin_src javascript
  const t0 = performance.now();

  // function for which the time to be calculated
  const updatedTasks = recalculateFloat(gantt);

  const t1 = performance.now();
  console.log('Call to recalculateFloat took ' + (t1 - t0) + ' milliseconds.');
#+end_src
*** For checking all the Event Listeners on the Page in Google Chrome
#+begin_src javascript
  const items = Array.prototype.slice
    .call(document.querySelectorAll('*'))
    .map(function(element) {
      const listeners = getEventListeners(element);
      return {
        element: element,
        listeners: Object.keys(listeners).map(function(k) {
          return { event: k, listeners: listeners[k] };
        })
      };
    })
    .filter(function(item) {
      return item.listeners.length;
    });
#+end_src
*** For removing duplicates from an Array
#+begin_src javascript
  function removeDuplicates(myArr, prop) {
    return myArr.filter((obj, pos, arr) => {
      return arr.map(mapObj => mapObj[prop]).indexOf(obj[prop]) === pos;
    });
  }
#+end_src
*** For checking if an Object is Empty or not
#+begin_src javascript
  function isEmpty(obj) {
    for (var key in obj) {
      if (obj.hasOwnProperty(key)) {
        return false;
      }
    }
    return true;
  }
#+end_src
*** For removing the truncated zeroes from the begining of a Number
#+begin_src javascript
  var yourString = '00001';
  yourString = Number(yourString).toString(); // output => "1"
#+end_src
*** This method can also be applied for changing the percent with decimal points
#+begin_src javascript
    // input = 0.00, output = "0"
    // input = 1.31, output = "1.31"
    const number = Number(percent).toString();
#+end_src
*** Use default arguments instead of short circuiting or conditionals
  Default arguments are often cleaner than short circuiting. Be aware that if you use them, your function will only provide default values for undefined arguments. Other "falsy" values such as '', "", false, null, 0, and NaN, will not be replaced by a default value.
**** Bad
#+begin_src javascript
  function createMicrobrewery(name) {
    const breweryName = name || 'Hipster Brew Co.';
    // ...
  }
#+end_src
**** Good
#+begin_src javascript
  function createMicrobrewery(name = 'Hipster Brew Co.') {
    // ...
  }
#+end_src
*** Allowing only Integers Value in Input Type Number
#+begin_src javascript
  doNotAllowDecimal(e) {
    if (
      (e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) &&
      (e.keyCode < 96 || e.keyCode > 105)
    ) {
      e.preventDefault();
    }
  }
#+end_src
*** Allow only one Minus and numbers in input type text
#+begin_src html
  <input type="text" maxlength="10" id="myInput" />
#+end_src

#+begin_src javascript
  var input = document.getElementById('myInput');

  input.onkeypress = function(e) {
    e = e || window.event;
    var charCode = typeof e.which == 'number' ? e.which : e.keyCode;

    // Allow non-printable keys
    if (!charCode || charCode == 8 /* Backspace */) {
      fd;
      return;
    }

    var typedChar = String.fromCharCode(charCode);

    // Allow numeric characters
    if (/\d/.test(typedChar)) {
      return;
    }

    // Allow the minus sign (-) if the user enters it first
    if (typedChar == '-' && this.value == '') {
      return;
    }

    // In all other cases, suppress the event
    return false;
  };
#+end_src
*** Capitalize first letter of every word or the String
#+begin_src javascript
  const capitalize = s => {
    if (typeof s !== 'string') return '';
    return s.charAt(0).toUpperCase() + s.slice(1);
  };
#+end_src
*** Moment.js warning of deprecation
  To get rid of the warning, you need to either:
**** Pass in an ISO formatted version of your date string
#+begin_src javascript
    moment('2014-04-23T09:54:51');
#+end_src
**** Pass in the string you have now, but tell Moment what format the string is in
#+begin_src javascript
    moment('Wed, 23 Apr 2014 09:54:51 +0000', 'ddd, DD MMM YYYY HH:mm:ss ZZ');
#+end_src
**** Convert your string to a JavaScript Date Object and then pass that into Moment
#+begin_src javascript
    moment(new Date('Wed, 23 Apr 2014 09:54:51 +0000'));
#+end_src
**** The last option is a built-in fallback that Moment supports for now, with the deprecated console warning. They say they won't support this fallback in future releases. They explain that using new Date('my date') is too unpredictable.
*** Deep Cloning
#+begin_src javascript
function deepClone(obj) {
  let clone = Object.assign({}, obj);
  Object.keys(clone).forEach(key =>
		(clone[key] = typeof obj[key] === 'object' ?
			deepClone(obj[key]) :
			obj[key])
  );
	if(Array.isArray(obj)) {
		clone.length = obj.length;
		return Array.from(clone);
	} else {
		return clone;
	}
};
#+end_src
** GitHub Repositories
*** [[https://github.com/ryanmcdermott/clean-code-javascript][clean-code-javascript]]
*** [[https://github.com/BuildingXwithJS/bxjs-weekly][bxjs-weekly]]
*** [[https://github.com/airbnb/javascript][Airbnb JavaScript Style Guide]]
** Articles
*** [[https://codeburst.io/javascript-currying-vs-partial-application-4db5b2442be8][Javascript- Currying VS Partial Application]]
*** [[https://medium.com/better-programming/an-intro-to-javascript-for-experienced-programmers-who-could-use-a-strong-dose-of-fundamentals-31535030616b][An Intro to Javascript for Experienced Programmers Who Could Use a Strong Dose of Fundamentals]]
** Websites
*** [[https://javascript.info/][Javascript Info Website]]
